// <auto-generated />
namespace ContactApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MG0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MG0));
        
        string IMigrationMetadata.Id
        {
            get { return "201606030444085_MG0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
